package exception_handling_program_june6;

public class Test43 {
	public static void main(String[] args)  throws Exception
	{
		methodA();
	}

	public static void methodA() throws Exception
	{
		System.out.println("Completed..");
	}
}
